export const CREATE_MENTOR = "CREATE_MENTOR";
export const DELETE_MENTOR = "DELETE_MENTOR";
export const GET_MENTORS = "GET_MENTORS";
export const SHOW_ERROR = "SHOW_ERROR";
export const GET_MENTOR_DETAILS = "GET_MENTOR_DETAILS";
export const UPDATE_MENTOR = "UPDATE_MENTOR";
export const FLUSH_MENTOR = "FLUSH_MENTOR";
